spring:
  application:
    name: Sep12P

server:
  port: 8088


eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8087/eureka/
    fetch-registry: true
